# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "webmoney"
  s.version = "0.0.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Oryol"]
  s.date = "2012-11-21"
  s.email = "eagle.alex@gmail.com"
  s.extra_rdoc_files = [
    "ChangeLog",
    "README.md"
  ]
  s.files = [
    "ChangeLog",
    "Gemfile",
    "README.md",
    "RUNNING_TESTS",
    "VERSION",
    "lib/interfaces.rb",
    "lib/messenger.rb",
    "lib/passport.rb",
    "lib/purse.rb",
    "lib/request_result.rb",
    "lib/request_retval.rb",
    "lib/request_xml.rb",
    "lib/signer.rb",
    "lib/webmoney.rb",
    "lib/wmid.rb",
    "rakefile",
    "spec/spec_helper.rb",
    "spec/unit/balance_spec.rb",
    "spec/unit/check_user.rb",
    "spec/unit/iconv_spec.rb",
    "spec/unit/interfaces_spec.rb",
    "spec/unit/login_spec.rb",
    "spec/unit/messenger_spec.rb",
    "spec/unit/passport_spec.rb",
    "spec/unit/purse_spec.rb",
    "spec/unit/signer_spec.rb",
    "spec/unit/time_spec.rb",
    "spec/unit/trust_spec.rb",
    "spec/unit/webmoney_spec.rb",
    "spec/unit/wmid_spec.rb",
    "ssl-certs/AddTrust_External_Root.crt",
    "ssl-certs/WebMoneyCA.crt",
    "ssl-certs/ca_bundle.crt",
    "webmoney.gemspec"
  ]
  s.require_paths = ["lib"]
  s.rubyforge_project = "webmoney"
  s.rubygems_version = "1.8.24"
  s.summary = "Webmoney interfaces and native wmsigner"
  s.test_files = ["Gemfile", "spec/unit/balance_spec.rb", "spec/unit/passport_spec.rb", "spec/unit/iconv_spec.rb", "spec/unit/login_spec.rb", "spec/unit/trust_spec.rb", "spec/unit/wmid_spec.rb", "spec/unit/webmoney_spec.rb", "spec/unit/interfaces_spec.rb", "spec/unit/signer_spec.rb", "spec/unit/check_user.rb", "spec/unit/time_spec.rb", "spec/unit/messenger_spec.rb", "spec/unit/purse_spec.rb", "spec/spec_helper.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
  end
end

